### ISSUE TITLE
Digital Envelope errors?

### ISSUE THREAD

**Issue by VashJuan** [Farata/angulartypescript#27]
1st:  I love & have used your book A LOT!
![20220106_152118](https://user-images.githubusercontent.com/8594671/148466828-1fe80ce2-46c9-441e-8c4a-9708098ac177.jpg)

2nd: I can deal with outdated Angular warnings, but do NOT know how to resolve the following

``opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
``
errors. **Any ideas? Thanks!**

PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05> ng serve -o
Node.js version v17.0.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
Your global Angular CLI version (13.1.2) is greater than your local version (12.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
⠸ Generating browser application bundles (phase: building)...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:144:18)
    at BulkUpdateDecorator.update (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:104:8)
    at NormalModule._initBuildHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:839:17)
    at handleParseResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:904:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:995:4
    at processResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:718:11)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:778:5
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at runSyncOrAsync (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:143:11)
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:250:2)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:144:18)
    at BulkUpdateDecorator.update (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:104:8)
    at NormalModule._initBuildHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:839:17)
    at handleParseResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:904:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:995:4
    at processResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:718:11)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:778:5
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at runSyncOrAsync (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:143:11)
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:250:2)
⠼ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:144:18)
    at BulkUpdateDecorator.update (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:104:8)
    at NormalModule._initBuildHash (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:839:17)
    at handleParseResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:904:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:995:4
    at processResult (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:718:11)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\webpack\lib\NormalModule.js:778:5
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at context.callback (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05\node_modules\css-loader\dist\index.js:182:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
PS D:\Projects\Angular\Angular-Projects-Second-Edition\Chapter05>

**Comment by VashJuan** [comment]
Oh sorry, using Evergreen Angular extension to VSCode I got it to work. Yeah!

**Comment by eliasab16** [comment]
I still have this issue. The abovementioned solution didn't work for me. Other online forum suggestions also didn't work, such as setting the NODE_OPTIONS=--openssl-legacy-provider. 

Help please.
